# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# https://docs.warp.dev/features/sessions/launch-configurations
#
# All launch configurations are stored under ~/.warp/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Work
windows:
  - tabs:
      - title: AHUB
        layout:
          split_direction: vertical
          panes:
            - cwd: /Users/joelevo/Projects/evosys/alarmhub/server
              is_focused: true
              commands:
                - exec: npm run serve
            - split_direction: horizontal
              panes:
                - cwd: /Users/joelevo/Projects/evosys/alarmhub/client
                  commands:
                    - exec: npm run serve
                - cwd: /Users/joelevo/Projects/evosys/alarmhub/map
                  commands:
                    - exec: npm run serve
        color: red
      - title: NVIM
        layout:
          cwd: /Users/joelevo/Projects/evosys/alarmhub
        color: red
      - title: CONSOLE
        layout:
          cwd: /Users/joelevo/Projects/evosys/alarmhub
        color: red
  - tabs:
      - title: FLOR
        layout:
          split_direction: vertical
          panes:
            - cwd: /Users/joelevo/Projects/evosys/floriplan/server
              is_focused: true
              commands:
                - exec: npm run serve
            - cwd: /Users/joelevo/Projects/evosys/floriplan/client
              commands:
                - exec: npm run serve
        color: magenta
      - title: NVIM
        layout:
          cwd: /Users/joelevo/Projects/evosys/floriplan
        color: magenta
      - title: CONSOLE
        layout:
          cwd: /Users/joelevo/Projects/evosys/floriplan
        color: magenta
  - tabs:
      - title: SPOT
        layout:
          split_direction: vertical
          panes:
            - cwd: /Users/joelevo/Projects/evosys/spotpilot/server
              is_focused: true
              commands:
                - exec: npm run serve
            - cwd: /Users/joelevo/Projects/evosys/spotpilot/client
              commands:
                - exec: npm run serve
        color: green
      - title: NVIM
        layout:
          cwd: /Users/joelevo/Projects/evosys/spotpilot
        color: green
      - title: CONSOLE
        layout:
          cwd: /Users/joelevo/Projects/evosys/spotpilot
        color: green
  - tabs:
      - title: ALDI
        layout:
          split_direction: vertical
          panes:
            - cwd: /Users/joelevo/Projects/evosys/alarmdisplay/server
              is_focused: true
              commands:
                - exec: npm run serve
            - split_direction: horizontal
              panes:
                - cwd: /Users/joelevo/Projects/evosys/alarmdisplay/client
                  commands:
                    - exec: npm run serve
                - cwd: /Users/joelevo/Projects/evosys/alarmdisplay/display
                  commands:
                    - exec: npm run serve
        color: yellow
      - title: NVIM
        layout:
          cwd: /Users/joelevo/Projects/evosys/alarmdisplay
        color: yellow
      - title: CONSOLE
        layout:
          cwd: /Users/joelevo/Projects/evosys/alarmdisplay
        color: yellow
  - tabs:
      - title: MYEV
        layout:
          split_direction: vertical
          panes:
            - cwd: /Users/joelevo/Projects/evosys/myevosys/server
              is_focused: true
              commands:
                - exec: npm run serve
            - split_direction: horizontal
              panes:
                - cwd: /Users/joelevo/Projects/evosys/myevosys/login
                  commands:
                    - exec: npm run serve
                - cwd: /Users/joelevo/Projects/evosys/myevosys/client
                  commands:
                    - exec: npm run serve
        color: blue
      - title: NVIM
        layout:
          cwd: /Users/joelevo/Projects/evosys/myevosys
        color: blue
      - title: CONSOLE
        layout:
          cwd: /Users/joelevo/Projects/evosys/myevosys
        color: blue
