# ./kanata.toml

[def.aliases]
hyper = { O = "C-A-S-M" } # C=Ctrl, A=Alt/Opt, S=Shift, M=Command
caps = "capslock"
esc  = "escape"

[[def.layers]]
name = "main"
keys = [
  { key = "caps", action = { tap = "esc", hold = "hyper", hold_timeout = 200 } }
]

[[def.layers]]
name = "hyper"
keys = [
  { key = "t", action = ["M-space", { T = "Terminal", D = 50 }, "ret"] },
]